Programa -> ListaElementos
ListaElementos -> Elemento ListaElementos
ListaElementos ->  
Elemento -> IncludeDecl
Elemento -> TypedefDecl
Elemento -> FuncaoDecl
IncludeDecl -> # ID < ID . ID >
TypedefDecl -> typedef struct { ListaCampos } ID ;
ListaCampos -> DeclaracaoVar ListaCampos
ListaCampos ->  
Tipo -> int
Tipo -> double
Tipo -> ID
DeclaracaoVar -> Tipo ListaIDs ;
ListaIDs -> ID , ListaIDs
ListaIDs -> ID
FuncaoDecl -> Tipo ID ( ListaParams ) Bloco
ListaParams -> Parametro , ListaParams
ListaParams -> Parametro
ListaParams ->  
Parametro -> Tipo ID
Parametro -> Tipo ID [ ]
Bloco -> { ListaComandos }
ListaComandos -> Comando ListaComandos
ListaComandos ->  
Comando -> DeclaracaoVar
Comando -> ID = Exp ;
Comando -> Acesso = Exp ;
Comando -> if ( Exp ) Bloco
Comando -> if ( Exp ) Bloco else Bloco
Comando -> while ( Exp ) Bloco
Comando -> for ( DeclaracaoVar Exp ; Atualizacao ) Bloco
Comando -> return Exp ;
Comando -> return ;
Comando -> Exp ;
Atualizacao -> ID = Exp
Atualizacao -> ++ ID
Atualizacao -> -- ID
Atualizacao -> ID ++
Atualizacao -> ID --
Atualizacao ->  
Exp -> Exp || ExpAnd
Exp -> ExpAnd
ExpAnd -> ExpAnd && ExpEq
ExpAnd -> ExpEq
ExpEq -> ExpEq == ExpRel
ExpEq -> ExpEq != ExpRel
ExpEq -> ExpRel
ExpRel -> ExpRel < ExpAdd
ExpRel -> ExpRel <= ExpAdd
ExpRel -> ExpRel > ExpAdd
ExpRel -> ExpRel >= ExpAdd
ExpRel -> ExpAdd
ExpAdd -> ExpAdd + ExpMult
ExpAdd -> ExpAdd - ExpMult
ExpAdd -> ExpMult
ExpMult -> ExpMult * Fator
ExpMult -> ExpMult / Fator
ExpMult -> ExpMult % Fator
ExpMult -> Fator
Fator -> NUM_INT
Fator -> NUM_DEC
Fator -> ID
Fator -> Acesso
Fator -> ChamadaFuncao
Fator -> ( Exp )
Fator -> ! Fator
Acesso -> ID [ Exp ]
Acesso -> ID . ID
Acesso -> Acesso . ID
ChamadaFuncao -> ID ( ListaArgs )
ListaArgs -> Exp , ListaArgs
ListaArgs -> Exp
ListaArgs ->  